# TouchDesigner Network: Simple Feedback Loop
# Resolution: 1920x1080
# Generated by TD Network Creator Mode
# 
# This example demonstrates a basic feedback loop with noise input
# Run in TouchDesigner textport with: exec(open('path/to/simple_feedback_loop.py').read())

# Create base container for organization
feedback_container = op('/').create(containerCOMP, 'feedback_system')

# Create noise source
noise = feedback_container.create(noiseTOP, 'noise_source')
noise.par.resolution1 = 1920
noise.par.resolution2 = 1080
noise.par.type = 'sparse'
noise.par.period = 5
noise.par.amplitude = 0.5

# Create feedback TOP
feedback = feedback_container.create(feedbackTOP, 'feedback_loop')
feedback.par.feedbacktarget = 'feedback_target'

# Create level adjustment
level = feedback_container.create(levelTOP, 'level_adjust')
level.par.brightness1 = 0.95  # Slight decay for feedback
level.par.opacity = 0.9

# Create composite for mixing
composite = feedback_container.create(compositeTOP, 'mixer')
composite.par.operand = 'over'

# Create output null
output = feedback_container.create(nullTOP, 'output')
output.par.display = True
output.par.viewer = True

# Create feedback target null
feedback_target = feedback_container.create(nullTOP, 'feedback_target')

# Connect the network
noise.outputConnectors[0].connect(composite.inputConnectors[0])
feedback.outputConnectors[0].connect(level.inputConnectors[0])
level.outputConnectors[0].connect(composite.inputConnectors[1])
composite.outputConnectors[0].connect(feedback.inputConnectors[0])
feedback.outputConnectors[0].connect(feedback_target.inputConnectors[0])
composite.outputConnectors[0].connect(output.inputConnectors[0])

# Layout operators for clarity
noise.nodeX = -200
noise.nodeY = 0
feedback.nodeX = 0
feedback.nodeY = 100
level.nodeX = 200
level.nodeY = 100
composite.nodeX = 0
composite.nodeY = 0
output.nodeX = 200
output.nodeY = -100
feedback_target.nodeX = 0
feedback_target.nodeY = 200

print("Feedback loop network created successfully!")
print(f"Output available at: {output.path}")